// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillForgeLibrary.Models;

#nullable disable

namespace Skillforge.Data.Migrations
{
    [DbContext(typeof(SkillForgeDB))]
    [Migration("20260313051640_InitialMig")]
    partial class InitialMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Skillforge.Domain.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .HasColumnType("int");

                    b.Property<int>("EnrollmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("AttendanceID", "EnrollmentID");

                    b.HasIndex("EnrollmentID");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Skillforge.Domain.Audit", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Findings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HRID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("CHAR(5)");

                    b.Property<string>("Scope")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AuditID");

                    b.HasIndex("HRID");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("Skillforge.Domain.AuditLog", b =>
                {
                    b.Property<string>("AuditID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Resource")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .HasColumnType("CHAR(5)");

                    b.HasKey("AuditID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Skillforge.Domain.Competency", b =>
                {
                    b.Property<int>("CompetencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetencyID"));

                    b.Property<string>("Description")
                        .HasColumnType("CHAR(50)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("CHAR(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CHAR(10)");

                    b.HasKey("CompetencyID");

                    b.ToTable("Competency");
                });

            modelBuilder.Entity("Skillforge.Domain.ComplianceRecord", b =>
                {
                    b.Property<int>("ComplianceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplianceID"));

                    b.Property<int>("CertificationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("CHAR(5)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ComplianceID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ComplianceRecord");
                });

            modelBuilder.Entity("Skillforge.Domain.Course", b =>
                {
                    b.Property<string>("CourseID")
                        .HasColumnType("char(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("char(50)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("char(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("char(20)");

                    b.Property<string>("TrainerID")
                        .HasColumnType("char(5)");

                    b.HasKey("CourseID");

                    b.HasIndex("TrainerID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Skillforge.Domain.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .HasColumnType("int");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("EnrollmentID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("Skillforge.Domain.Module", b =>
                {
                    b.Property<string>("ModuleID")
                        .HasColumnType("char(5)");

                    b.Property<string>("ContentURI")
                        .HasColumnType("char(50)");

                    b.Property<string>("CourseID")
                        .HasColumnType("char(5)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("char(10)");

                    b.Property<string>("Title")
                        .HasColumnType("char(20)");

                    b.HasKey("ModuleID");

                    b.HasIndex("CourseID");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("Skillforge.Domain.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("CourseID")
                        .HasColumnType("char(5)");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("CHAR(5)");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("CourseID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("Skillforge.Domain.SkillGap", b =>
                {
                    b.Property<int>("SkillGapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillGapID"));

                    b.Property<int>("CompetencyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateIdentified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("CHAR(5)");

                    b.Property<int>("GapLevel")
                        .HasColumnType("int");

                    b.HasKey("SkillGapID");

                    b.HasIndex("CompetencyID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("SkillGap");
                });

            modelBuilder.Entity("Skillforge.Domain.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("CHAR(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("CHAR(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CHAR(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("CHAR(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("CHAR(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CHAR(15)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Skillforge.Domain.Attendance", b =>
                {
                    b.HasOne("Skillforge.Domain.Enrollment", "EnrollmentIdNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("EnrollmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnrollmentIdNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.Audit", b =>
                {
                    b.HasOne("Skillforge.Domain.User", "HRUser")
                        .WithMany()
                        .HasForeignKey("HRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HRUser");
                });

            modelBuilder.Entity("Skillforge.Domain.AuditLog", b =>
                {
                    b.HasOne("Skillforge.Domain.User", "UserIdNavigation")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("UserIdNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.ComplianceRecord", b =>
                {
                    b.HasOne("Skillforge.Domain.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Skillforge.Domain.Course", b =>
                {
                    b.HasOne("Skillforge.Domain.User", "UserIDNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("TrainerID");

                    b.Navigation("UserIDNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.Module", b =>
                {
                    b.HasOne("Skillforge.Domain.Course", "CourseIDNavigation")
                        .WithMany("Modules")
                        .HasForeignKey("CourseID");

                    b.Navigation("CourseIDNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.Report", b =>
                {
                    b.HasOne("Skillforge.Domain.Course", "CourseIDNavigation")
                        .WithMany()
                        .HasForeignKey("CourseID");

                    b.HasOne("Skillforge.Domain.User", "EmployeeIDNavigation")
                        .WithMany()
                        .HasForeignKey("EmployeeID");

                    b.Navigation("CourseIDNavigation");

                    b.Navigation("EmployeeIDNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.SkillGap", b =>
                {
                    b.HasOne("Skillforge.Domain.Competency", "Competency")
                        .WithMany("SkillGaps")
                        .HasForeignKey("CompetencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skillforge.Domain.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Skillforge.Domain.Competency", b =>
                {
                    b.Navigation("SkillGaps");
                });

            modelBuilder.Entity("Skillforge.Domain.Course", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Skillforge.Domain.Enrollment", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Skillforge.Domain.User", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
