// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillForgeLibrary.Models;

#nullable disable

namespace SkillForgeLibrary.Migrations
{
    [DbContext(typeof(SkillForgeDB))]
    [Migration("20260309095602_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillForgeLibrary.Models.Course", b =>
                {
                    b.Property<string>("CourseID")
                        .HasColumnType("char(5)");

                    b.Property<string>("Description")
                        .HasColumnType("char(50)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("char(10)");

                    b.Property<string>("Title")
                        .HasColumnType("char(20)");

                    b.Property<string>("TrainerID")
                        .HasColumnType("char(5)");

                    b.HasKey("CourseID");

                    b.HasIndex("TrainerID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("SkillForgeLibrary.Models.Module", b =>
                {
                    b.Property<string>("ModuleID")
                        .HasColumnType("char(5)");

                    b.Property<string>("ContentURI")
                        .HasColumnType("char(50)");

                    b.Property<string>("CourseID")
                        .HasColumnType("char(5)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("char(10)");

                    b.Property<string>("Title")
                        .HasColumnType("char(20)");

                    b.HasKey("ModuleID");

                    b.HasIndex("CourseID");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("SkillForgeLibrary.Models.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("CHAR(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("CHAR(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("CHAR(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("CHAR(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("CHAR(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CHAR(15)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SkillForgeLibrary.Models.Course", b =>
                {
                    b.HasOne("SkillForgeLibrary.Models.User", "UserIDNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("TrainerID");

                    b.Navigation("UserIDNavigation");
                });

            modelBuilder.Entity("SkillForgeLibrary.Models.Module", b =>
                {
                    b.HasOne("SkillForgeLibrary.Models.Course", "CourseIDNavigation")
                        .WithMany("Modules")
                        .HasForeignKey("CourseID");

                    b.Navigation("CourseIDNavigation");
                });

            modelBuilder.Entity("SkillForgeLibrary.Models.Course", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("SkillForgeLibrary.Models.User", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
